/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Stitch Design System (Material Design 3) ──────────────────────
        "tertiary-fixed": "#ffd9dc",
        "on-tertiary-container": "#ffcace",
        "on-secondary-fixed-variant": "#344e00",
        "surface-container-highest": "#e0e4dd",
        "on-primary-container": "#9ae9ae",
        "primary": "#005129",
        "surface-container-high": "#e6e9e2",
        "on-tertiary-fixed-variant": "#792d39",
        "secondary-container": "#b4f349",
        "primary-fixed": "#a5f4b8",
        "inverse-on-surface": "#eef2eb",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb2b9",
        "secondary-fixed": "#b7f64c",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#005229",
        "outline-variant": "#bfc9be",
        "inverse-primary": "#89d89e",
        "outline": "#707a70",
        "on-surface": "#181d19",
        "on-background": "#181d19",
        "primary-fixed-dim": "#89d89e",
        "surface-dim": "#d7dbd4",
        "secondary": "#466800",
        "surface": "#f7faf3",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "background": "#f7faf3",
        "surface-container": "#ebefe8",
        "on-secondary-container": "#496d00",
        "on-surface-variant": "#404940",
        "on-secondary": "#ffffff",
        "surface-variant": "#e0e4dd",
        "on-error": "#ffffff",
        "tertiary-container": "#96434f",
        "primary-container": "#1a6b3c",
        "on-tertiary-fixed": "#3f0110",
        "surface-tint": "#1b6c3d",
        "surface-container-low": "#f1f5ee",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#00210d",
        "on-secondary-fixed": "#121f00",
        "secondary-fixed-dim": "#9cd92f",
        "surface-bright": "#f7faf3",
        "tertiary": "#782c38",
        "inverse-surface": "#2d322d",
        "on-error-container": "#93000a",

        // ── Legacy helpers (used by other pages) ──────────────────────────
        "primary-hover": "#003e1f",
        "slate-text": "#1F2937",
        "cool-grey": "#4B5563",
        "canvas": "#FFFFFF",
        "surface-muted": "#F3F4F6",
        "alert-success-bg": "#D1FAE5",
        "alert-success-text": "#065F46",
        "alert-warning-bg": "#FEF3C7",
        "alert-warning-text": "#92400E",
        "alert-danger-bg": "#FEE2E2",
        "alert-danger-text": "#991B1B",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        margin: "24px",
        sm: "8px",
        xl: "32px",
        md: "16px",
        gutter: "16px",
        base: "8px",
        lg: "24px",
        xxl: "48px",
      },
      fontFamily: {
        "body-sm": ["DM Sans", "sans-serif"],
        "button": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "label-bold": ["DM Sans", "sans-serif"],
        "h1": ["Barlow Condensed", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "h2": ["Barlow Condensed", "sans-serif"],
        "h3": ["Barlow Condensed", "sans-serif"],
        // Legacy
        "sans": ["DM Sans", "Inter", "system-ui", "sans-serif"],
        "display": ["Barlow Condensed", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "button": ["16px", { lineHeight: "1", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
        "h1": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "h2": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h3": ["24px", { lineHeight: "1.2", letterSpacing: "0em", fontWeight: "600" }],
      },
      boxShadow: {
        card: '0 1px 3px 0 rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.08)',
        modal: '0 20px 60px -10px rgb(0 0 0 / 0.18)',
        glow: '0 0 20px rgb(16 185 129 / 0.35)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
